Havoc_And_Haven/Controllers/BattleController.cs
using Havoc_And_Haven.BL;
using Havoc_And_Haven.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Havoc_And_Haven.Controllers {
    public class BattleController : Controller {
        private readonly BattleService _battleService;

        public BattleController(BattleService battleService) {
            _battleService = battleService;
        }

        public IActionResult Index() {
            List<Battle> battles = _battleService.GetAllBattles();
            ViewBag.Heros = _battleService.GetHeroes();
            ViewBag.Villians = _battleService.GetVillains();
            return View(battles);
        }

        [HttpGet]
        public IActionResult Create() {
            ViewBag.Crises = _battleService.GetAllCrises();
            ViewBag.Heros = _battleService.GetHeroes();
            ViewBag.Villians = _battleService.GetVillains();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Battle battle) {
            if (ModelState.IsValid) {
                _battleService.CreateBattle(battle);
                return RedirectToAction("Index");
            }

            ViewBag.Crises = _battleService.GetAllCrises();
            ViewBag.Heros = _battleService.GetHeroes();
            ViewBag.Villians = _battleService.GetVillains();
            return View(battle);
        }

        [HttpPost]
        public IActionResult Delete(int id) {
            Battle battle = _battleService.GetBattleById(id);
            if (battle != null) {
                _battleService.DeleteBattle(id);
                return RedirectToAction("Index");
            }
            return Content("Not found!");
        }

    }
}

Havoc_And_Haven/Controllers/LairController.cs
using Havoc_And_Haven.BLL;
using Havoc_And_Haven.Models;
using Microsoft.AspNetCore.Mvc;

namespace Havoc_And_Haven.Controllers
{
    public class LairController : Controller {
        private readonly LairService _lairService;
        private readonly LocationService _locationService;

        public LairController(LairService lairService, LocationService locationService) {
            _lairService = lairService;
            _locationService = locationService;
        }

        public IActionResult Index() {
            List<Lair> lairs = _lairService.GetAllLairs();
            return View(lairs);
        }

        [HttpGet]
        public IActionResult Create() {
            ViewBag.Locations = _locationService.GetAllLocations();

            return View(new Lair());
        }
        [HttpPost]
        public IActionResult Create(Lair lair) {
            if (ModelState.IsValid) {
                lair.Location = _locationService.GetLocationById(lair.LocationId);

                _lairService.AddLair(lair);

                return RedirectToAction("Index");
            }

            ViewBag.Locations = _locationService.GetAllLocations();
            return View(lair);
        }

        [HttpGet]
        public IActionResult Edit(int id) {
            Lair? lair = _lairService.GetLairById(id);
            if (lair == null) {
                return NotFound();
            }

            ViewBag.Locations = _locationService.GetAllLocations();

            return View(lair);
        }

        [HttpPost]
        public IActionResult Edit(Lair lair) {
            if (ModelState.IsValid) {
                _lairService.UpdateLair(lair);
                return RedirectToAction("Index");
            }

            ViewBag.Locations = _locationService.GetAllLocations();

            return View(lair);
        }

        [HttpGet]
        public IActionResult DeleteLair(int id) {
            Lair? lair = _lairService.GetLairById(id);
            if (lair == null) {
                return NotFound();
            }

            return View(lair);
        }

        [HttpPost]
        public IActionResult DeleteLairConfirmed(int id) {
            Lair? lair = _lairService.GetLairById(id);
            if (lair == null) {
                return NotFound();
            }

            _lairService.DeleteLair(id);

            return RedirectToAction("Index");
        }
    }
}

Havoc_And_Haven/Controllers/LocationController.cs
using Havoc_And_Haven.BLL;
using Havoc_And_Haven.Models;
using Microsoft.AspNetCore.Mvc;


namespace Havoc_And_Haven.Controllers
{
    public class LocationController : Controller
    {
        private readonly LocationService _LocationService;

        public LocationController(LocationService locationservice)
        {

            _LocationService = locationservice;
        }

        public IActionResult Index()
        {
            List<Location> locations = _LocationService.GetAllLocations();
            return View(locations);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Location());
        }

        [HttpPost]
        public IActionResult Create(Location location)
        {
            if (ModelState.IsValid)
            {
                _LocationService.Create(location);
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Location? location = _LocationService.GetAllLocations().FirstOrDefault(r => r.LocationId == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        [HttpPost]
        public IActionResult Edit(Location location)
        {
            if (ModelState.IsValid)
            {
                _LocationService.Edit(location);
                return RedirectToAction("Index");
            }

            return View(location);
        }

        [HttpGet]
        public IActionResult DeleteLocation(int id)
        {
            Location? location = _LocationService.GetLocationById(id);
            return View(location);
        }

        [HttpPost]
        public IActionResult DeleteLocationConfirmed(int id)
        {
            Location? location = _LocationService.GetLocationById(id);
            if (location == null)
            {
                return NotFound();
            }

            _LocationService.delete(id);

            return RedirectToAction("Index");
        }
    }
}
    

Havoc_And_Haven/Controllers/UsersController.cs
using Havoc_And_Haven.BLL;
using Havoc_And_Haven.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Havoc_And_Haven.Controllers
{
    public class UserController : Controller
    {
        private readonly UserService _userService;
        private readonly HeadquartersService _hqService;
        private readonly LairService _lairService;

        public UserController(UserService userService, HeadquartersService hqService, LairService lairService)
        {
            _userService = userService;
            _hqService = hqService;
            _lairService = lairService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Users> users = _userService.GetAllUsers();
            return View(users);
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            List<Headquarters> headquarters = _hqService.GetAllHeadquarters();
            List<Lair> lairs = _lairService.GetAllLairs();

            ViewBag.Headquarters = headquarters;
            ViewBag.Lairs = lairs;

            return View(new Users());
        }

        [HttpPost]
        public IActionResult AddUser(Users user)
        {
            if (ModelState.IsValid)
            {
                _userService.AddUser(user);
                return RedirectToAction("Index");
            }

            List<Headquarters> headquarters = _hqService.GetAllHeadquarters();
            List<Lair> lairs = _lairService.GetAllLairs();

            ViewBag.Headquarters = headquarters;
            ViewBag.Lairs = lairs;

            return View(user);
        }

        [HttpGet]
        public IActionResult EditUser(int id)
        {
            Users user = _userService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            List<Headquarters> headquarters = _hqService.GetAllHeadquarters();
            List<Lair> lairs = _lairService.GetAllLairs();

            ViewBag.Headquarters = headquarters;
            ViewBag.Lairs = lairs;

            return View(user);
        }

        [HttpPost]
        public IActionResult EditUser(Users user)
        {
            if (ModelState.IsValid)
            {
                _userService.UpdateUser(user);
                return RedirectToAction("Index");
            }

            List<Headquarters> headquarters = _hqService.GetAllHeadquarters();
            List<Lair> lairs = _lairService.GetAllLairs();

            ViewBag.Headquarters = headquarters;
            ViewBag.Lairs = lairs;

            return View(user);
        }

        [HttpGet]
        public IActionResult ViewProfile(int id)
        {
            Users user = _userService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpGet]
        public IActionResult DeleteUser(int id)
        {
            Users user = _userService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost]
        public IActionResult DeleteUserConfirmed(int id)
        {
            _userService.DeleteUser(id);
            return RedirectToAction("Index");
        }
    }
}

Havoc_And_Haven/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Havoc_And_Haven</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nosifer&family=Rubik+Mono+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Lexend:wght@100..900&family=Merriweather+Sans:ital,wght@0,300..800;1,300..800&family=Merriweather:ital,opsz,wght@0,18..144,300..900;1,18..144,300..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Outfit:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Havoc_And_Haven.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Havoc_And_Haven</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Headquarters" asp-action="Index">Headquarters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lair" asp-action="Index">Lairs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Battle" asp-action="Index">Battle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CrisisEvent" asp-action="Index">CrisisEvent</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Havoc_And_Haven - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>